title: Zoom Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://zoomstatus.netlify.com'
params:
  alwaysKeepBrandColor: true
  autoRefresh: true
  brand: ffffff
  customTabs:
    - link: >-
        https://docs.google.com/forms/d/1QZ-y7UKKcwkHJ04NLfLCHVGczo4ZEiu8HwwnFycXBvQ/
      name: Report an Issue
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disrupted: FF8C00
  down: DC143C
  googleAnalytics: UA-00000000-1
  incidentPostsPerPage: 10
  logo: /img/6d700943-ede4-4c60-a6ca-5eb4f3e2c94a.jpeg
  notice: '708090'
  ok: 228B22
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: ZoomWiki - Wikipedia, but better.
      name: ZoomWiki
    - description: ZoomVPN - Browse freely.
      name: ZoomVPN
    - description: Heroku - PHP hosting for all.
      name: Heroku
  useLargeHeaderDesign: false
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
