title: Zoom Status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: 'https://zoomstatus.netlify.com'
params:
  alwaysKeepBrandColor: true
  autoRefresh: true
  brand: ffffff
  customTabs: []
  dateFormat: 'January 2, 2006 at 3:04 PM'
  description: >-
    We continuously monitor the status of our services and if there are any
    interruptions, a note will be posted here.
  disrupted: cc4400
  down: e60000
  googleAnalytics: UA-00000000-1
  incidentPostsPerPage: 10
  logo: /img/6d700943-ede4-4c60-a6ca-5eb4f3e2c94a.jpeg
  notice: 24478f
  ok: ff8fff
  shortDateFormat: '15:04 — Jan 2'
  systems:
    - description: The status of the Zoon
      name: ZoomWiki
    - description: The status of the VPN.
      name: ZoomVPN
    - description: The status of Heroku and it’s components.
      name: Heroku
  useLargeHeaderDesign: true
  useLogo: true
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
